import type { Metadata } from "next";
import BackToTopButton from "./components/BackToTopButton";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "./components/ToastProvider";
import { ThemeProvider } from "./components/ThemeProvider";
import { AnimatedBar } from "./components/AnimatedBar";
import Image from "next/image";
import Link from "next/link";

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Energy Stock",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${jetbrainsMono.variable} font-mono antialiased min-h-screen text-neutral-100 dark:text-green-100 selection:bg-green-300/60 selection:text-green-900`}
        style={{ 
          background: 'linear-gradient(to bottom, #000000 0%, #000000 10%, #32de84 70%, #000000 90%, #000000 100%)',
          backgroundColor: '#000000'
        }}
        suppressHydrationWarning
      >
        <ThemeProvider>
          <ToastProvider>
            <div className="relative isolate min-h-screen flex flex-col">
              <header 
                className="relative z-50 w-full py-4 sm:py-6 px-4 lg:px-10 flex items-center justify-between border-b border-neutral-800/30"
                style={{ backgroundColor: '#0a0a0a' }}
              >
                <h1 className="text-2xl sm:text-3xl md:text-4xl font-extrabold tracking-tight flex items-center cursor-pointer">
                  <span className="text-[#32de84]">
                    <Link href="/">Energy</Link>
                  </span>
                  <Link href="/">
                    <Image
                      src="/logo.png"
                      alt="Logo"
                      width={100}
                      height={100}
                      className="mx-2 h-10 w-10 sm:h-10 sm:w-10 inline-block"
                      priority
                    />
                  </Link>
                  <span className="text-[#32de84]">
                    <Link href="/" className="cursor-pointer">
                      Stock
                    </Link>
                  </span>
                </h1>
              </header>
              <AnimatedBar />
              <main className="z-10 flex-1 w-full px-7 pb-12 lg:px-10 pt-4">
                {children}
              </main>
              <footer className="z-10 w-full pb-12 my-5 text-center text-s text-white">
                <ul className="space-y-4">
                  <li>
                    <span>
                      © {new Date().getFullYear()} waipu.tv engineering
                    </span>
                  </li>
                  <li className="flex justify-center items-center gap-4">
                    <Link
                      href="/admin/login"
                      className="inline-block p-6 py-2 rounded-full border border-black text-black text-lg transition-all hover:bg-neutral-800"
                      style={{ backgroundColor: '#32de84' }}
                    >
                      Dashboard
                    </Link>
                      <BackToTopButton
                        className="inline-block p-6 py-2 rounded-full border border-white text-white text-lg transition-all hover:bg-neutral-800"
                        style={{ backgroundColor: '#000000' }}
                      />
                  </li>
                </ul>

                <div className="mt-6 flex flex-wrap justify-center items-center text-[10px] tracking-wide text-white">
                  <a
                    href="https://nextjs.org/docs"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="underline decoration-2 transition-all hover:decoration-[#32de84]"
                  >
                    Next.js
                  </a>
                  <span className="px-2">|</span>
                  <a
                    href="https://www.prisma.io/docs/getting-started"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="underline decoration-2 transition-all hover:decoration-[#32de84]"
                  >
                    Prisma
                  </a>
                  <span className="px-2">|</span>
                  <a
                    href="https://supabase.com/docs"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="underline decoration-2 transition-all hover:decoration-[#32de84]"
                  >
                    Supabase
                  </a>
                  <span className="px-2">|</span>
                  <a
                    href="https://tailwindcss.com/docs"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="underline decoration-2 transition-all hover:decoration-[#32de84]"
                  >
                    Tailwind CSS
                  </a>
                  <span className="px-2">|</span>
                  <a
                    href="https://www.framer.com/motion/"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="underline decoration-2 transition-all hover:decoration-[#32de84]"
                  >
                    Framer Motion
                  </a>
                </div>
              </footer>
            </div>
          </ToastProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
